// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SkyFleet.Data.Context;

#nullable disable

namespace SkyFleet.Data.Migrations
{
    [DbContext(typeof(SkyFleetContext))]
    [Migration("20250709015036_Inital")]
    partial class Inital
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SkyFleet.Data.Model.Aeronaves", b =>
                {
                    b.Property<int>("AeronaveId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AeronaveId"));

                    b.Property<int?>("AltitudMaxima")
                        .HasColumnType("int");

                    b.Property<int?>("CapacidadCombustible")
                        .HasColumnType("int");

                    b.Property<int?>("CapacidadPasajeros")
                        .HasColumnType("int");

                    b.Property<int?>("ConsumoXHora")
                        .HasColumnType("int");

                    b.Property<double?>("CostoXHora")
                        .HasColumnType("float");

                    b.Property<string>("DescripcionAeronave")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescripcionCategoria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescripcionMotor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Licencia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModeloAvion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Peso")
                        .HasColumnType("float");

                    b.Property<int?>("Rango")
                        .HasColumnType("int");

                    b.Property<string>("Registracion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("VelocidadMaxima")
                        .HasColumnType("float");

                    b.Property<int>("estadoId")
                        .HasColumnType("int");

                    b.HasKey("AeronaveId");

                    b.ToTable("aeronaves");
                });

            modelBuilder.Entity("SkyFleet.Data.Model.Rutas", b =>
                {
                    b.Property<int>("RutaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RutaId"));

                    b.Property<string>("destino")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("distancia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("duracion")
                        .HasColumnType("int");

                    b.Property<string>("origen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RutaId");

                    b.ToTable("rutas");
                });

            modelBuilder.Entity("SkyFleet.Data.Model.TipoVuelo", b =>
                {
                    b.Property<int>("tipoVueloId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("tipoVueloId"));

                    b.Property<string>("descripcionTipoVuelo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombreVuelo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("tipoVueloId");

                    b.ToTable("tipoVuelo");
                });
#pragma warning restore 612, 618
        }
    }
}
