// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SkyFleet.Data.Context;

#nullable disable

namespace SkyFleet.Data.Migrations
{
    [DbContext(typeof(SkyFleetContext))]
    [Migration("20250706021040_SkyFleet")]
    partial class SkyFleet
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SkyFleet.Data.Model.Rutas", b =>
                {
                    b.Property<int>("RutaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RutaId"));

                    b.Property<string>("destino")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("distancia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("duracion")
                        .HasColumnType("int");

                    b.Property<string>("origen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RutaId");

                    b.ToTable("rutas");
                });

            modelBuilder.Entity("SkyFleet.Data.Model.TipoVuelo", b =>
                {
                    b.Property<int>("tipoVueloId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("tipoVueloId"));

                    b.Property<string>("descripcionTipoVuelo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombreVuelo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("tipoVueloId");

                    b.ToTable("tipoVuelo");
                });
#pragma warning restore 612, 618
        }
    }
}
